#!/usr/bin/env bash

set -e

DEFAULT_CONFIG_PREFIX="default"
CONFIG_SUFFIX=".conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

if [[ `uname` == "Darwin" ]]; then
    OS_CONFIG="mac"
elif [[ `uname -r | tr '[:upper:]' '[:lower:]'` == *"microsoft"* ]]; then
    BASE_OS_CONFIG="linux-base"
    OS_CONFIG="linux-wsl"
else
    BASE_OS_CONFIG="linux-base"
    OS_CONFIG="linux-debian"
fi

for conf in ${DEFAULT_CONFIG_PREFIX} ${OS_CONFIG} ${@}; do
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${conf}${CONFIG_SUFFIX}"
done
