tap "weaveworks/tap"

# Packages
brew "bat"
brew "fd"
brew "flux"
brew "git-delta"
brew "gitops"
brew "helm"
brew "kubernetes-cli"
brew "kubeseal"
brew "jq"
brew "ncurses"
brew "neovim"
brew "tree-sitter"
brew "vivid"
brew "exa"
brew "fzf"
brew "pyenv"
brew "pyenv-virtualenv"
brew "xz"
brew "z"
# brew "source-highlight"
# brew "pandoc"

# Official Amazon AWS command-line interface
brew "awscli"

# Integrated shell for working with the AWS CLI
brew "aws-shell"

# Utility for easily assuming AWS IAM roles from the command-line
brew "aws-vault"

# Tool to generate documentation from Terraform modules
brew "terraform-docs"

# Linter for Terraform files
brew "tflint"

# Framework for managing multi-language pre-commit hooks
brew "pre-commit"

# Prevent cloud misconfigurations during build-time for IaC tools
brew "checkov"

# Terraform version manager
brew "tfenv"
